# Generated by Django 5.2.4 on 2025-07-30 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cakes.store'),
            preserve_default=False,
        ),
    ]
