# Generated by Django 5.2.4 on 2025-08-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0007_customerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='store',
        ),
        migrations.AddField(
            model_name='cake',
            name='stores',
            field=models.ManyToManyField(related_name='cakes', to='cakes.store'),
        ),
    ]
