# Generated by Django 5.2.4 on 2025-08-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0010_category_cake_category_review_storereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
